version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      security:
        applies-to: security-updates
        patterns:
          - "*"
      version-updates:
        applies-to: version-updates
        patterns:
          - "*"