name: Check Python Version
description: Check if the version in the pyproject.toml file has changed
inputs:
  path:
    description: The path to the directory containing the pyproject.toml file
    required: true
    default: ${{ github.workspace }}
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        path: main
        ref: main
    - uses: actions/checkout@v4
      with:
        path: current
        ref: ${{ github.sha }}
    - name: Check Version
      shell: bash
      run: |
        if [[ ! -f $GITHUB_WORKSPACE/main/${{ inputs.path }}/pyproject.toml ]]; then
          echo "No pyproject.toml file found in main branch"
          exit 0
        fi
        MAIN_PATH=$GITHUB_WORKSPACE/main/${{ inputs.path }}
        CURRENT_PATH=$GITHUB_WORKSPACE/current/${{ inputs.path }}
        OLD_VERSION=$(cat $MAIN_PATH/pyproject.toml| grep -o "version.*" | cut -d'=' -f2 | tr -d '"' | tr -d ' ')
        NEW_VERSION=$(cat $CURRENT_PATH/pyproject.toml| grep -o "version.*" | cut -d'=' -f2 | tr -d '"' | tr -d ' ')
        rm -rf $GITHUB_WORKSPACE/current
        rm -rf $GITHUB_WORKSPACE/main
        if [ "$OLD_VERSION" == "$NEW_VERSION" ]; then
          echo "Version $NEW_VERSION is the same as $OLD_VERSION"
          exit 1
        fi
