name: PySpark execution
description: This action allows you to execute code, written for Spark, Databricks or other similar engines.

inputs:
  image_tag:
    description: The tag of the docker image to use
    required: true

runs:
  using: composite
  steps:
    - name: Execute python tests
      shell: bash
      run: |
        chmod +x ./.docker/entrypoint.sh
        IMAGE_TAG=${{ inputs.image_tag }} docker-compose -f .devcontainer/docker-compose.yml run --rm -u root -w //workspaces/opengeh-python-packages packages ./.docker/entrypoint.sh
