name: PySpark execution
description: This action allows you to execute code, written for Spark, Databricks or other similar engines.

inputs:
  tests_filter_expression:
    description: Filter expression to use with pytest. Read description in 'entrypoint.sh'.
    required: true

runs:
  using: composite
  steps:
    - name: Execute python tests
      shell: bash
      run: |
        chmod +x ./.docker/entrypoint.sh
        docker-compose -f .devcontainer/docker-compose.yml run --rm -u root -w //workspaces/opengeh-python-packages packages ./.docker/entrypoint.sh "${{ inputs.tests_filter_expression }}"
