name: PySpark execution
description: This action allows you to execute code, written for Spark, Databricks or other similar engines.

runs:
  using: composite
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Execute python tests
      shell: bash
      run: |
        chmod +x ./.docker/entrypoint.sh
        docker-compose -f .devcontainer/docker-compose.yml run --rm -u root -w //workspaces/opengeh-python-packages python-unit-test ./.docker/entrypoint.sh
