name: PySpark-slim image builder
description: Builds and optional publish a container image to GitHub Packages
inputs:
  pyspark_download_url:
    required: true
    description: url from where pyspark can be downloaded
  pyspark_version:
    required: true
    description: Version of PySpark - becomes part of the image tag
  image_postfix:
    required: true
    description: Post for the image tag
  publish_to_github_packages:
    required: false
    default: "false"
    description: if 'true' the image is published to GitHub Packages - default is 'false'

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        build-args: |
          spark_download_url=${{ inputs.pyspark_download_url }}
          spark_version=${{ inputs.pyspark_version }}
        context: container-images/pyspark-slim
        push: ${{ inputs.publish_to_github_packages }}
        tags: |
          ghcr.io/energinet-datahub/pyspark-slim:${{ inputs.pyspark_version }}-${{ inputs.image_postfix }}
