services:
    geh_common:
        image: geh-utilities:latest
        build:
            args:
                SPARK_VERSION: 3.5.4
                UBUNTU_VERSION: '24.04'
                UV_VERSION: 0.5.15
            context: ..
            dockerfile: .docker/Dockerfile
        command: sleep infinity
        volumes:
        - ..:/workspace:cached
    