from datetime import datetime

from pyspark.sql import SparkSession
from pyspark.sql.dataframe import DataFrame

import tests.helpers.datetime_formatter as date_time_formatter
from package.schemas.silver.metering_points_silver_schema import (
    metering_points_silver_schema,
)
from .metering_point_defaults import MeteringPointDefaults

date_time_formatting_string = "%Y-%m-%dT%H:%M:%S%z"

default_date = date_time_formatter.format_datetime("01-01-2020T23:00:00+0000")
default_startdate = date_time_formatter.format_datetime("01-01-2020T23:00:00+0000")
default_enddate = date_time_formatter.format_datetime("01-01-2021T23:00:00+0000")


def build(
    spark: SparkSession,
    metering_point_id: str = MeteringPointDefaults.metering_point_id,
    btd_business_trans_doss_id: int = MeteringPointDefaults.btd_business_trans_doss_id,
    metering_point_state_id: int = MeteringPointDefaults.metering_point_state_id,
    metering_grid_area_id: str = MeteringPointDefaults.metering_grid_area_id,
    type_of_mp: str = MeteringPointDefaults.type_of_mp,
    physical_status_of_mp: str = MeteringPointDefaults.physical_status_of_mp,
    meter_reading_occurrence: str | None = MeteringPointDefaults.meter_reading_occurrence,
    settlement_method: str = MeteringPointDefaults.settlement_method,
    balance_supplier_id: str | None = MeteringPointDefaults.balance_supplier_id,
    valid_from_date: datetime = default_startdate,
    valid_to_date: datetime | None = default_enddate,
    created: datetime = datetime.now(),
) -> DataFrame:
    dc = [
        {
            "metering_point_id": metering_point_id,
            "asset_type": None,
            "balance_responsible_party_id": "5799994000343",
            "balance_resp_party_start_date": default_date,
            "balance_supplier_id": balance_supplier_id,
            "balance_supplier_start_date": default_date,
            "blocked_for_linking": "0",
            "btd_business_trans_doss_id": btd_business_trans_doss_id,
            "consumer_category": "111",
            "consumer_cvr": "11111111",
            "contact_1_address_code": None,
            "contact_1_attention": None,
            "contact_1_building_number": None,
            "contact_1_city_name": None,
            "contact_1_city_subdivision_name": None,
            "contact_1_contact_name1": None,
            "contact_1_contact_name2": None,
            "contact_1_country_name": None,
            "contact_1_dar_reference": None,
            "contact_1_email_address": None,
            "contact_1_floor_id": None,
            "contact_1_mobile_number": None,
            "contact_1_mpt_metering_point_contact_id": None,
            "contact_1_municipality_code": None,
            "contact_1_phone_number": None,
            "contact_1_postcode": None,
            "contact_1_post_box": None,
            "contact_1_protected_address": None,
            "contact_1_room_id": None,
            "contact_1_same_as_mp_address": None,
            "contact_1_street_code": None,
            "contact_1_street_name": None,
            "contact_2_address_code": None,
            "contact_2_attention": None,
            "contact_2_building_number": None,
            "contact_2_city_name": None,
            "contact_2_city_subdivision_name": None,
            "contact_2_contact_name1": None,
            "contact_2_contact_name2": None,
            "contact_2_country_name": None,
            "contact_2_dar_reference": None,
            "contact_2_email_address": None,
            "contact_2_floor_id": None,
            "contact_2_mobile_number": None,
            "contact_2_mpt_metering_point_contact_id": None,
            "contact_2_municipality_code": None,
            "contact_2_phone_number": None,
            "contact_2_postcode": None,
            "contact_2_post_box": None,
            "contact_2_protected_address": None,
            "contact_2_room_id": None,
            "contact_2_same_as_mp_address": None,
            "contact_2_street_code": None,
            "contact_2_street_name": None,
            "contact_3_address_code": None,
            "contact_3_attention": None,
            "contact_3_building_number": None,
            "contact_3_city_name": None,
            "contact_3_city_subdivision_name": None,
            "contact_3_contact_name1": None,
            "contact_3_contact_name2": None,
            "contact_3_country_name": None,
            "contact_3_dar_reference": None,
            "contact_3_email_address": None,
            "contact_3_floor_id": None,
            "contact_3_mobile_number": None,
            "contact_3_mpt_metering_point_contact_id": None,
            "contact_3_municipality_code": None,
            "contact_3_phone_number": None,
            "contact_3_postcode": None,
            "contact_3_post_box": None,
            "contact_3_protected_address": None,
            "contact_3_room_id": None,
            "contact_3_same_as_mp_address": None,
            "contact_3_street_code": None,
            "contact_3_street_name": None,
            "contact_4_address_code": None,
            "contact_4_attention": None,
            "contact_4_building_number": None,
            "contact_4_city_name": None,
            "contact_4_city_subdivision_name": None,
            "contact_4_contact_name1": None,
            "contact_4_contact_name2": None,
            "contact_4_country_name": None,
            "contact_4_dar_reference": None,
            "contact_4_email_address": None,
            "contact_4_floor_id": None,
            "contact_4_mobile_number": None,
            "contact_4_mpt_metering_point_contact_id": None,
            "contact_4_municipality_code": None,
            "contact_4_phone_number": None,
            "contact_4_postcode": None,
            "contact_4_post_box": None,
            "contact_4_protected_address": None,
            "contact_4_room_id": None,
            "contact_4_same_as_mp_address": None,
            "contact_4_street_code": None,
            "contact_4_street_name": None,
            "created_timestamp": "2016-08-05T13:38:01.539000",
            "data_access_cvr": "11111111",
            "disconnection_type": "D02",
            "energy_timeseries_measure_unit": "KWH",
            "estimated_annual_volume": 0,
            "first_consumer_cpr": None,
            "first_consumer_party_name": "Christopher Hitchens",
            "first_consumer_party_ref": None,
            "from_grid_area": None,
            "fuel_type": None,
            "hourly_time_series": None,
            "location_building_number": "1",
            "location_city_name": "Groningen",
            "location_city_subdivision_name": "Hoogkerk",
            "location_country_name": "DK",
            "location_dar_reference": None,
            "location_floor_id": "2",
            "location_location_description": "Behind the Kitchen Door",
            "location_mp_address_wash_instructions": "D01",
            "location_municipality_code": "108",
            "location_postcode": "9745",
            "location_room_id": None,
            "location_street_code": "1233",
            "location_street_name": "Eemsgolaan",
            "metering_grid_area_id": metering_grid_area_id,
            "metering_point_state_id": metering_point_state_id,
            "metering_point_sub_type": None,
            "meter_counter_digits": "6.3",
            "meter_counter_multiply_factor": 1,
            "meter_counter_type": "D02",
            "meter_counter_unit": "KWH",
            "meter_number": "685183",
            "meter_reading_occurrence": meter_reading_occurrence,
            "mp_capacity": None,
            "mp_connection_type": None,
            "mp_reading_characteristics": None,
            "net_settlement_group": "0",
            "parent_metering_point_id": None,
            "physical_metering_point": "1",
            "physical_status_of_mp": physical_status_of_mp,
            "power_limit_a": 90,
            "power_limit_kw": 3500,
            "power_plant_gsrn": None,
            "product": "8716867000030",
            "product_obligation": None,
            "protected_name": None,
            "pso_exempt": None,
            "scheduled_meter_reading_date01": None,
            "scheduled_meter_reading_date02": None,
            "scheduled_meter_reading_date03": None,
            "scheduled_meter_reading_date04": None,
            "scheduled_meter_reading_date05": None,
            "scheduled_meter_reading_date06": None,
            "scheduled_meter_reading_date07": None,
            "scheduled_meter_reading_date08": None,
            "scheduled_meter_reading_date09": None,
            "scheduled_meter_reading_date10": None,
            "scheduled_meter_reading_date11": None,
            "scheduled_meter_reading_date12": None,
            "second_consumer_cpr": None,
            "second_consumer_party_name": None,
            "second_consumer_party_ref": None,
            "settlement_method": settlement_method,
            "submission_delay": None,
            "sub_type_of_mp": "D01",
            "tax_reduction": "1",
            "tax_settlement_date": "2015-12-31T23:00:00",
            "to_grid_area": None,
            "type_of_mp": type_of_mp,
            "valid_from_date": valid_from_date,
            "valid_to_date": valid_to_date,
            "web_access_code": "ABCD1234",
            "created": created,
        },
    ]

    return spark.createDataFrame(dc, schema=metering_points_silver_schema)
