name: Reusable CI

# The concept of `core` must be removed prior to moving these workflows and
# actions to a public repository. The `core` concept is specific to the
# Measurements project and is used to group packages that are released together.

on:
  workflow_call:
    inputs:
      packages_directory:
        type: string
        description: |
          Directory to search for python packages in. This recursively searches
          for directories containing a pyproject.toml file. All directories
          discovered are considered packages. Any package with changes will
          be tested, and given successful tests, a prerelease will be created
          with under the tag "<package_name>_<pull_request_number>".
          Defaults to workspace root.
        required: true
        default: ${{ github.workspace }}
      tests_directory:
        type: string
        description: |
          Directory to search for tests in. This recursively searches for
          directories containing a test directory. All directories discovered
          are considered test directories. Defaults to "tests".
        required: false
        default: tests
      azure_spn_id:
        type: string
        description: The Azure SPN ID for the integration test environment
        required: false
        default: ""
      azure_tenant_id:
        type: string
        description: The Azure tenant ID for the integration test environment
        required: false
        default: ""
      azure_subscription_id:
        type: string
        description: The Azure subscription ID for the integration test environment
        required: false
        default: ""
      azure_keyvault_url:
        type: string
        description: The Azure KeyVault URL for the integration test environment
        required: false
        default: ""
    secrets:
      dh3serviceaccount_privatekey:
        required: true
        description: Used in ci_base job to authenticate with the DataHub3 service account

permissions:
  id-token: write
  contents: write
  issues: read
  checks: write
  pull-requests: write

jobs:
  #
  # License and Markdown Check
  #
  ci_base:
    uses: Energinet-DataHub/.github/.github/workflows/ci-base.yml@v14
    with:
      skip_license_check: true
    secrets:
      dh3serviceaccount_privatekey: ${{ secrets.dh3serviceaccount_privatekey }}

  #
  # Build Package Matrix
  #
  ci_matrix:
    name: Build Package Matrix
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.package_matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Discover Pyproject
        uses: ./.github/actions/python-discover-pyproject
        id: package_matrix
        with:
          path: ${{ inputs.packages_directory }}

  #
  # Test Packages
  #
  ci_test:
    name: Test Packages
    runs-on: ubuntu-24.04
    needs: ci_matrix
    # Environment is used when using OIDC to login and access the integration test environment
    environment: AzureAuth
    env:
      # Necessary to manage Azure resources from automated tests
      AZURE_KEYVAULT_URL: ${{ inputs.azure_keyvault_url }}
    strategy:
      matrix:
        inputs: ${{ fromJson(needs.ci_matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if ${{ matrix.inputs.name }} has changed
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            is_changed:
              - ${{ matrix.inputs.path }}/**

      - name: Test ${{ matrix.inputs.name }}
        uses: ./.github/actions/python-test
        if: ${{ steps.changes.outputs.is_changed == 'true' }}
        with:
          name: ${{ matrix.inputs.name }}
          path: ${{ matrix.inputs.path }}
          tests_path: ${{ inputs.tests_directory }}
          azure_spn_id: ${{ inputs.azure_spn_id }}
          azure_tenant_id: ${{ inputs.azure_tenant_id }}
          azure_subscription_id: ${{ inputs.azure_subscription_id }}

      - name: Create prerelease for ${{ matrix.inputs.name }}
        uses: ./.github/actions/github-create-prerelease
        if: ${{ steps.changes.outputs.is_changed == 'true' }}
        with:
          name: ${{ matrix.inputs.name }}
          path: ${{ matrix.inputs.path }}
          issue-number: ${{ github.event.number }}
