name: CD - Python test Docker image

# The design of this workflow is inspired by: https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions
on:
  pull_request:
    branches:
      - main
    paths:
      - .docker/**
      - .github/workflows/cd-docker-test-image.yml
  push:
    branches:
      - main
    paths:
      - .docker/**
      - .github/workflows/cd-docker-test-image.yml

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/python-unit-test
  IS_PULL_REQUEST_TRIGGERED: ${{ github.event_name == 'pull_request' }}
  CONTEXT_PATH: ./.docker/
  CONTAINER_REGISTRY_USER: dh-system-account

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.CONTAINER_REGISTRY_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Declare Docker image name
        id: image-name
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set tag environmental variable
        run: |
          if [[ ${{ env.IS_PULL_REQUEST_TRIGGERED }} == true ]]; then
              echo "TAG=:pre-release-pr${{ github.event.pull_request.number }}" >> "$GITHUB_ENV"
          else
              echo "TAG=:latest" >> "$GITHUB_ENV"
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.CONTEXT_PATH }}
          push: true
          tags: ${{ steps.image-name.outputs.lowercase }}${{ env.TAG }}
