# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CD

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  ci_reusable:
    name: Continuous Integration
    uses: ./.github/workflows/reusable-ci.yml
    with:
      packages_directory: ${{ github.workspace }}
      tests_directory: tests
      azure_tenant_id: ${{ vars.integration_test_azure_tenant_id }}
      azure_subscription_id: ${{ vars.integration_test_azure_subscription_id }}
      azure_spn_id: ${{ vars.integration_test_azure_spn_id_oidc }}
      azure_keyvault_url: ${{ vars.integration_test_azure_keyvault_url }}
    secrets:
      dh3serviceaccount_privatekey: ${{ secrets.dh3serviceaccount_privatekey }}

  cd_reusable:
    name: Continuous Deployment
    uses: ./.github/workflows/reusable-cd.yml
    needs: [ci_reusable]
    with:
      subsystem_name: opengeh-common
      notification_email: 5543d1b6.energinet.onmicrosoft.com@emea.teams.ms # Wholesale - Dev Test
      sender_email: ${{ vars.email_internal_sender }}
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      send_grid_api_key: ${{ secrets.sendgrid_instance_system_notifications_api_key }}
