name: CI orchestrator

on:
  pull_request:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
    - name: Verify if merge is allowed
      run: |
        echo 'Hello world'
