name: CI orchestrator

on:
  pull_request:
    branches:
      - main

jobs:
  # License and Markdown Check
  ci_base:
    uses: Energinet-DataHub/.github/.github/workflows/ci-base.yml@v12
    with:
      skip_license_check: true
    secrets:
      pat_token: ${{ secrets.internal_github_pat }}

  changes:
    uses: ./.github/workflows/detect-changes.yml

  ci_docker:
    needs: changes
    if: ${{ needs.changes.outputs.docker == 'true' }}
    uses: ./.github/workflows/python-build-and-push-docker-image.yml

  create_release:
    needs: [changes]
    if: ${{ needs.changes.outputs.telemetry == 'true' || needs.changes.outputs.spark-sql-migrations == 'true' }}
    uses: ./.github/workflows/create-release-tag.yml
    secrets: inherit

  # Branch policy status check
  allow_merge_ci_orchestrator:
    runs-on: ubuntu-latest
    needs: [ci_base, ci_docker, create_release]
    if: |
      always()
    steps:
      - name: Verify if merge is allowed
        run: |
          echo "${{ toJSON(needs) }}"
          if [[ ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }} = true ]]; then
              echo "Failed"
              exit 1
          fi
