name: CI orchestrator

on:
  pull_request:
    branches:
      - main

jobs:
  # License and Markdown Check
  ci_base:
    uses: Energinet-DataHub/.github/.github/workflows/ci-base.yml@v12
    with:
      skip_license_check: true
    secrets:
      pat_token: ${{ secrets.internal_github_pat }}

  changes:
    uses: ./.github/workflows/detect-changes.yml

  create_release:
    needs: [changes]
    if: ${{ needs.changes.outputs.telemetry == 'true' || needs.changes.outputs.spark-sql-migrations == 'true' }}
    uses: ./.github/workflows/create-release-tag.yml
    secrets: inherit

  databricks_ci_test:
    uses: Energinet-DataHub/.github/.github/workflows/python-ci.yml@v12
    with:
      operating_system: dh3-ubuntu-20.04-4core
      path_static_checks: ./source/telemetry
      # documented here https://github.com/Energinet-DataHub/opengeh-migration/tree/main/source/MigrationTools#styling-and-formatting
      ignore_errors_and_warning_flake8: E501,F401,E402,E203,W503
      test_report_path: ./source/telemetry/tests

  # Branch policy status check
  allow_merge_ci_orchestrator:
    runs-on: ubuntu-latest
    needs: [ci_base, create_release]
    if: |
      always()
    steps:
      - name: Verify if merge is allowed
        run: |
          echo "${{ toJSON(needs) }}"
          if [[ ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }} = true ]]; then
              echo "Failed"
              exit 1
          fi
