name: CI orchestrator

on:
  pull_request:
    branches:
      - main
  merge_group:
    types: [checks_requested]

jobs:
  #
  # Reusable CI
  #
  ci_unit:
    name: Unit tests
    uses: ./.github/workflows/reusable-ci.yml
    with:
      packages_directory: ${{ github.workspace }}
      tests_directory: tests/unit
    secrets:
      dh3serviceaccount_privatekey: ${{ secrets.dh3serviceaccount_privatekey }}

  ci_integration:
    name: Integration tests
    uses: ./.github/workflows/reusable-ci.yml
    with:
      packages_directory: ${{ github.workspace }}
      tests_directory: tests/integration
      azure_tenant_id: ${{ vars.integration_test_azure_tenant_id }}
      azure_subscription_id: ${{ vars.integration_test_azure_subscription_id }}
      azure_spn_id: ${{ vars.integration_test_azure_spn_id_oidc }}
      azure_keyvault_url: ${{ vars.integration_test_azure_keyvault_url }}
    secrets:
      dh3serviceaccount_privatekey: ${{ secrets.dh3serviceaccount_privatekey }}

  # Branch policy status check
  allow_merge_ci_orchestrator:
    runs-on: ubuntu-latest
    needs: [ci_unit, ci_integration]
    if: |
      always()
    steps:
      - name: Verify if merge is allowed
        run: |
          echo "${{ toJSON(needs) }}"
          if [[ ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }} = true ]]; then
              echo "Failed"
              exit 1
          fi
