name: Create release tag

on:
  workflow_call: {}

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: Energinet-DataHub/.github/.github/actions/create-release-tag@v12
        with:
          # BE AWARE --> Updating to a new MAJOR version will delete deprecated versions on a nightly schedule.
          # See https://github.com/Energinet-DataHub/.github#release-procedure for details
          major_version: 1
          minor_version: 1
          patch_version: 4
          repository_path: Energinet-DataHub/opengeh-python-packages
        env:
          GH_TOKEN: ${{ secrets.internal_github_pat }} # Organization level token needed for github code search to target all repositories
