name: Create release tag

on:
  workflow_call: {}

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: Energinet-DataHub/.github/.github/actions/github-create-token@v13
        name: Generate Github token
        id: generate_token
        with:
          app_id: ${{ vars.dh3serviceaccount_appid }}
          private_key: ${{ secrets.dh3serviceaccount_privatekey }}

      - name: Create release
        uses: Energinet-DataHub/.github/.github/actions/create-release-tag@v13
        with:
          # BE AWARE --> Updating to a new MAJOR version will delete deprecated versions on a nightly schedule.
          # See https://github.com/Energinet-DataHub/.github#release-procedure for details
          major_version: 1
          minor_version: 4
          patch_version: 1
          repository_path: Energinet-DataHub/opengeh-python-packages
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
