name: Detect changes

# DESCRIPTION:
# This workflow will determine which categories of jobs should be executed,
# based on detected changes.
# It should be used by the 'ci-orchestrator.yml' to ensure they both use
# the same path's to detect changes

on:
  workflow_call:
    outputs:
      telemetry:
        value: ${{ jobs.changes.outputs.telemetry }}
      spark_sql_migrations:
        value: ${{ jobs.changes.outputs.spark_sql_migrations }}
      docker:
        value: ${{ jobs.changes.outputs.docker }}

jobs:
  changes:
    name: Determine relevant jobs
    runs-on: ubuntu-latest
    outputs:
      telemetry: ${{ steps.filter.outputs.telemetry }}
      spark_sql_migrations: ${{ steps.filter.outputs.spark_sql_migrations }}
      docker: ${{ steps.docker_changed.outputs.any_changed }}

    steps:
      - name: Checkout repository
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/checkout@v3

      - name: Detect file changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            telemetry:
              - 'source/telemetry/**'
            spark_sql_migrations:
              - 'source/spark-sql-migrations/**'
            docker:
              - .docker/**
              - .github/workflows/cd-docker-test-image.yml

      - name: Get changed files
        id: getfile
        run: |
          git fetch origin ${{ github.base_ref }}
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.event.pull_request.head.sha }} $(git merge-base ${{ github.event.pull_request.head.sha }} FETCH_HEAD))"

