name: Detect changes

# DESCRIPTION:
# This workflow will determine which categories of jobs should be executed,
# based on detected changes.
# It should be used by the 'ci-orchestrator.yml' to ensure they both use
# the same path's to detect changes

on:
  workflow_call:
    outputs:
      telemetry:
        value: ${{ jobs.changes.outputs.telemetry }}
      spark_sql_migrations:
        value: ${{ jobs.changes.outputs.spark_sql_migrations }}
      docker:
        value: ${{ jobs.changes.outputs.docker }}

jobs:
  changes:
    name: Determine relevant jobs
    runs-on: ubuntu-latest
    outputs:
      telemetry: ${{ steps.filter.outputs.telemetry }}
      spark_sql_migrations: ${{ steps.filter.outputs.spark_sql_migrations }}
      docker: ${{ steps.docker_changed.outputs.any_changed }}

    steps:
      - name: Checkout repository
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/checkout@v3

      - name: Detect file changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            telemetry:
              - 'source/telemetry/**'
            spark_sql_migrations:
              - 'source/spark-sql-migrations/**'
            docker:
              - .docker/**
              - .github/workflows/cd-docker-test-image.yml

      - name: Package content or build has changed
        id: docker_changed
        uses: tj-actions/changed-files@v41
        with:
          base_sha: ${{ github.sha }}
          since_last_remote_commit: true
          files: |
            .docker/**
            .github/workflows/cd-docker-test-image.yml
