# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Publish pyspark-slim image to ghcr.io

on:
  # Build, test, pack and publish release packages
  # Only executed if (*.)Commonm, (*.)FunctionApp or (*.)WebApp packages content or build scripts has changed; not if solution file, documentation or tests has changed
  push:
    branches:
      - main
    paths:
      - container-images/pyspark-slim/**
      - .github/workflows/pyspark-slim-publish.yml
  # Build, test, pack
  # Executed if App folder or build scripts has changed; including if documentation or tests has changed
  workflow_call: {}
  # Build, test, pack and publish prerelease packages
  # Executed if manually triggered
  workflow_dispatch: {}

jobs:
  build_and_publish_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    name: Build and publish pyspark-slim image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read versions from yaml
        uses: pietrobolcato/action-read-yaml@1.1.0
        id: build_config
        with:
          config: container-images/pyspark-slim/build-config.yml

      - name: Get Pull request info
        id: pr
        run: |
          echo "push_image=TRUE" >> $GITHUB_OUTPUT
          if [[ "${{ github.event.pull_request.merged }}" == "false" ]]
          then
            echo "push_image=FALSE" >> $GITHUB_OUTPUT
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          build-args: |
            spark_download_url=${{ steps.build_config.outputs.spark_download_url }}
            spark_version=${{ steps.build_config.outputs.spark_version }}
          context: container-images/pyspark-slim
          platforms: linux/amd64,linux/arm64
          push: ${{ steps.pr.outputs.push_image }}
          tags: |
            ghcr.io/energinet-datahub/pyspark-slim:${{ steps.build_config.outputs.spark_version }}-${{ steps.build_config.outputs.image_postfix }}
